apiVersion: v1
kind: ServiceAccount
metadata:
  name: user2
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-role-binding-user2
subjects:
  - kind: ServiceAccount
    name: user2
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-debian-pod-bound-token
  namespace: default
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: user2
      containers:
      - image: debian
        name: main
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: my-bound-token
          mountPath: /var/run/secrets/my-bound-token
      volumes:
      - name: my-bound-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 3600
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecretname
  annotations:
    kubernetes.io/service-account.name: user2